// Fallback / seed menu data. Used when Supabase has no rows yet.
// Same shape as Supabase rows (snake_case fields).

export const FALLBACK_CATEGORIES = [
  { id: 'cat-doner', name_en: 'Döner', name_ar: 'دونر', sort_order: 1 },
  { id: 'cat-burger', name_en: 'Burger', name_ar: 'برجر', sort_order: 2 },
  { id: 'cat-hotdog', name_en: 'Hot Dog', name_ar: 'هوت دوغ', sort_order: 3 },
  { id: 'cat-fries', name_en: 'Fries', name_ar: 'بطاطا', sort_order: 4 },
  { id: 'cat-drinks', name_en: 'Drinks', name_ar: 'مشروبات', sort_order: 5 },
];

export const FALLBACK_ITEMS = [
  {
    id: 'i1', category_id: 'cat-doner',
    name_en: 'Classic Döner', name_ar: 'دونر كلاسيك',
    desc_en: 'Tender marinated beef, crisp veggies, garlic sauce in warm flatbread.',
    desc_ar: 'لحم بقري متبل طري مع خضار طازجة وصلصة الثوم في خبز دافئ.',
    price: 8.5, rating: 4.8, rating_count: 124, available: true,
    image_url: 'https://images.unsplash.com/photo-1633321702518-7feccafb94d5?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: true, combo_price: 11.2,
  },
  {
    id: 'i2', category_id: 'cat-doner',
    name_en: 'Spicy Chicken Döner', name_ar: 'دونر دجاج حار',
    desc_en: 'Grilled chicken with our signature spicy harissa and pickled onions.',
    desc_ar: 'دجاج مشوي مع صلصة الهريسة الحارة وبصل مخلل.',
    price: 7.9, rating: 4.7, rating_count: 98, available: true,
    image_url: 'https://images.unsplash.com/photo-1638537125835-82acb38d3531?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: true, combo_price: 10.6,
  },
  {
    id: 'i3', category_id: 'cat-doner',
    name_en: 'Beef Döner Wrap', name_ar: 'لفافة دونر لحم',
    desc_en: 'Seasoned beef, tomato, lettuce, tahini & sumac in a toasted wrap.',
    desc_ar: 'لحم بقري متبل مع طماطم، خس، طحينة وسماق في لفافة محمصة.',
    price: 9.2, rating: 4.9, rating_count: 212, available: true,
    image_url: 'https://images.unsplash.com/photo-1699728088614-7d1d4277414b?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: true, combo_price: 11.9,
  },
  {
    id: 'i4', category_id: 'cat-doner',
    name_en: 'XL Döner Plate', name_ar: 'طبق دونر كبير',
    desc_en: 'Double-stacked döner with saffron rice and grilled vegetables.',
    desc_ar: 'دونر مضاعف مع أرز بالزعفران وخضار مشوية.',
    price: 13.5, rating: 4.9, rating_count: 156, available: false,
    image_url: 'https://images.unsplash.com/photo-1583060095186-852adde6b819?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: false,
  },
  {
    id: 'i5', category_id: 'cat-burger',
    name_en: 'Signature Cheeseburger', name_ar: 'برجر الجبنة',
    desc_en: 'Juicy Angus beef, aged cheddar, caramelized onions, smoked aioli.',
    desc_ar: 'لحم أنجوس عصيري، جبنة شيدر، بصل مكرمل، صلصة أيولي مدخنة.',
    price: 10.5, rating: 4.8, rating_count: 189, available: true,
    image_url: 'https://images.pexels.com/photos/2271107/pexels-photo-2271107.jpeg?auto=compress&cs=tinysrgb&w=800',
    has_combo: true, combo_price: 13.2,
  },
  {
    id: 'i6', category_id: 'cat-fries',
    name_en: 'Golden Fries', name_ar: 'بطاطا ذهبية',
    desc_en: 'Hand-cut, double-fried to crispy golden perfection. Sea salt.',
    desc_ar: 'بطاطا مقطعة يدوياً، مقلية مرتين حتى الذهبي. ملح البحر.',
    price: 4.5, rating: 4.6, rating_count: 87, available: true,
    image_url: 'https://images.pexels.com/photos/2282528/pexels-photo-2282528.jpeg?auto=compress&cs=tinysrgb&w=800',
    has_combo: false,
  },
  {
    id: 'i7', category_id: 'cat-hotdog',
    name_en: 'Chili Hot Dog', name_ar: 'هوت دوغ بالتشيلي',
    desc_en: 'All-beef frank topped with homemade chili, cheese & jalapeños.',
    desc_ar: 'نقانق لحم بقري مع تشيلي محلي، جبنة وفلفل هالبينو.',
    price: 6.9, rating: 4.7, rating_count: 102, available: true,
    image_url: 'https://images.unsplash.com/photo-1613482084286-41f25b486fa2?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: true, combo_price: 9.6,
  },
  {
    id: 'i8', category_id: 'cat-hotdog',
    name_en: 'Classic NY Dog', name_ar: 'هوت دوغ نيويورك',
    desc_en: 'Steamed bun, grilled frank, yellow mustard & sauerkraut.',
    desc_ar: 'خبز مبخر، نقانق مشوية، خردل أصفر ومخلل الملفوف.',
    price: 5.9, rating: 4.5, rating_count: 76, available: true,
    image_url: 'https://images.unsplash.com/photo-1612392166886-ee8475b03af2?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: true, combo_price: 8.6,
  },
  {
    id: 'i9', category_id: 'cat-hotdog',
    name_en: 'Loaded Cheese Dog', name_ar: 'هوت دوغ بالجبنة',
    desc_en: 'Melted cheddar, crispy bacon bits, chives & honey mustard.',
    desc_ar: 'جبنة شيدر ذائبة، قطع بيكون مقرمشة، ثوم معمر وخردل بالعسل.',
    price: 7.5, rating: 4.8, rating_count: 134, available: true,
    image_url: 'https://images.pexels.com/photos/12123657/pexels-photo-12123657.jpeg?auto=compress&cs=tinysrgb&w=800',
    has_combo: true, combo_price: 10.2,
  },
  {
    id: 'i10', category_id: 'cat-hotdog',
    name_en: 'Smokehouse Dog', name_ar: 'هوت دوغ مدخن',
    desc_en: 'Smoked sausage, crispy onions, BBQ sauce on a brioche bun.',
    desc_ar: 'سجق مدخن، بصل مقرمش، صلصة باربكيو على خبز بريوش.',
    price: 8.2, rating: 4.9, rating_count: 167, available: true,
    image_url: 'https://images.pexels.com/photos/28087251/pexels-photo-28087251.jpeg?auto=compress&cs=tinysrgb&w=800',
    has_combo: true, combo_price: 10.9,
  },
  {
    id: 'i11', category_id: 'cat-drinks',
    name_en: 'Craft Cola', name_ar: 'كولا',
    desc_en: 'Ice-cold craft cola, served in a glass bottle.',
    desc_ar: 'كولا باردة في زجاجة.',
    price: 2.5, rating: 4.4, rating_count: 52, available: true,
    image_url: 'https://images.unsplash.com/photo-1735643434124-f51889fa1f8c?crop=entropy&cs=srgb&fm=jpg&w=800&q=85',
    has_combo: false,
  },
  {
    id: 'i12', category_id: 'cat-drinks',
    name_en: 'Orange Fizz', name_ar: 'عصير برتقال فوار',
    desc_en: 'Sparkling orange soda with real fruit juice. Refreshing.',
    desc_ar: 'صودا برتقال فوارة بعصير الفاكهة الحقيقي. منعشة.',
    price: 2.8, rating: 4.5, rating_count: 41, available: true,
    image_url: 'https://images.pexels.com/photos/33450363/pexels-photo-33450363.jpeg?auto=compress&cs=tinysrgb&w=800',
    has_combo: false,
  },
];
